# Generated by Django 2.2.27 on 2022-04-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='unit_price',
        ),
    ]
